### ISSUE TITLE
Linux version request

### ISSUE THREAD

**Issue by at10ti0n** [Aksimant/miner_switcher#1]
Hi, do you have plans for implementing a linux version as well?

I believe most changes will be related to process starting/killing.

**Comment by Aksimant** [comment]
if u need i will linux support.

2017-09-27 16:24 GMT+03:00 Denis Salanta <notifications@github.com>:

**Comment by Aksimant** [comment]
I add linux version,  but i can't test normally it in Linux (have no video card there) Don't forget to create correct  miner_start.sh ( to open miner in new  terminal window with args) If there will be some ideas or some problems fell free to contact me.

**Comment by at10ti0n** [comment]
I'll give it a try this weekend. Thanks for the quick update!
